language: python
python:
  - 2.7

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

install:
  - conda update --yes conda
  - conda install --yes -c https://conda.binstar.org/osgeo gdal
  - conda install --yes scipy pillow matplotlib basemap nose
  - python setup.py install

script: "cd ..; nosetests nansat.tests"
