language: python
python:
  - 2.7
sudo: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh;
  - ./miniconda.sh -b -f -p $HOME/miniconda;
  - export PATH=$HOME/miniconda/bin:$PATH

install:
  - conda update -q --yes conda
  - conda install -q --yes -c conda-forge gdal numpy scipy matplotlib pillow netcdf4 nose
  - conda install -q --yes -c conda-forge basemap
  - export GDAL_DATA=/home/vagrant/miniconda/share/gdal/
  - export GEOS_DIR=/home/vagrant/miniconda/
  - python -c 'import gdal; print gdal.__file__'
  - python -c 'from mpl_toolkits.basemap import Basemap'
  - pip install coveralls
  - pip install cfunits
  - python setup.py install

script:
  - coverage run --omit=nansat/mappers/*,nansat/tests/* --source=nansat setup.py test

after_success:
  - coveralls


