language: python
python:
  - 2.7
sudo: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -f -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH

install:
  - conda update -q --yes conda
  - conda install -q --yes -c conda-forge gdal numpy pillow netcdf4 cfunits python-dateutil pythesint nose coveralls mock
  - python setup.py install

script:
  - coverage run --omit=nansat/mappers/*,nansat/tests/* --source=nansat setup.py test

after_success:
  - coveralls


