channels:
  - alevin
  - conda-forge
dependencies:
  - conda=2
  - sphinx>=1.4
  - sphinx-autobuild
  - sphinx_rtd_theme 
  - recommonmark
  - pandoc
  - nbconvert
  - ipykernel
  - python-dateutil
  - nansat>=1.0.4
  - mock
  - notebook
  - pip:
    - nbsphinx
